### ISSUE TITLE
Would you like to make this script library?

### ISSUE THREAD

**Issue by hhsprings** [jeorgen/align-videos-by-sound#7]
I'm using your script as module [like this](https://gist.github.com/hhsprings/f79cd7c1ff6d50f6ae3db115b41bf09b). I am very pleased that this script can be used as a library. If we can install with "setup.py", not only me but many Python users will be pleased. Looking at your other repositories, it seems that there are not many setup.py (not?). If you are unfamiliar with how to write this, I can write. How about? Once you have decided on the name of the package (like "xxx_video_edit_helper") and the name of the module (like "align.py"), I can make it (probably in an hour or a couple of hours at most).

If this is done, I think it will be easy to contribute other related scripts (like [your planned](https://github.com/jeorgen/align-videos-by-sound/pull/4#issuecomment-398677422)). Actually, I am pleased if [my script](https://gist.github.com/hhsprings/f79cd7c1ff6d50f6ae3db115b41bf09b) were managed together.

In addition, by setting it as a package of setup.py style, we can open the way to register with PyPI in the future.

**Comment by hhsprings** [comment]
For example, if source tree is like this:
```
./bin/align_videos_by_sound_track
./README.md
./requirements-python3.txt
./requirements.txt
./setup.py
./tests/testfiles/3-secs-in.mp4
./tests/testfiles/7-secs-in.mp4
./tests/testfiles/blank180.mp4
./tests/testfiles/full-44100Hz-stereo.mp4
./tests/testfiles/full-with-prepad-sec-180.mp4
./tests/testfiles/full.mp4
./xx_video_edit_helper/align_by_sound_track.py
./xx_video_edit_helper/__init__.py
```
and `./xx_video_edit_helper/__init__.py`:
```!python
__version__ = '0.0.1'
```
then `setup.py` is like this:
```python
#! /usr/bin/env python
from __future__ import with_statement

import os.path

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup
    extra = {'scripts': ["bin/align_videos_by_sound_track"]}
else:
    extra = {
        #'test_suite': 'align_videos_by_sound_track.test',
        'entry_points': {
            'console_scripts': [
                'align_videos_by_sound_track = xx_video_edit_helper.align_by_sound_track:main',
                ],
        },
    }


def get_version(fname=os.path.join('xx_video_edit_helper', '__init__.py')):
    with open(fname) as f:
        for line in f:
            if line.startswith('__version__'):
                return eval(line.split('=')[-1])


def get_long_description():
    descr = []
    for fname in ('README.md',):  # for PyPI, actually rst is suitable rather than markdown.
        with open(fname) as f:
            descr.append(f.read())
    return '\n\n'.join(descr)


setup(
    name="align_videos_by_sound_track",
    #license="MIT",    # choose as you like
    version=get_version(),
    #description="...",
    long_description=get_long_description(),
    #author="...",
    #author_email="...",
    #url="...",
    packages=[
        "xx_video_edit_helper",
        ],
    python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*',
    classifiers=[
        #"Development Status :: 6 - Mature",  # choose as you like
        "Environment :: Console",
        #"Intended Audience :: Developers",  # choose as you like
        #"License :: OSI Approved :: MIT License",  # choose as you like
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: Implementation :: CPython",
        "Programming Language :: Python :: Implementation :: PyPy",
        #"Topic :: Software Development",  # choose as you like
        "Topic :: Utilities",
    ],
    **extra)
```

**Comment by jeorgen** [comment]
Feel free make into an installable package, egg, wheel or what is called nowadays! :)

**Comment by hhsprings** [comment]
Can I make a PR? What about the names? (I will keep the script name to be placed in the `bin/`, but when making it as a package I would like to make the package name and module name appropriate.)

**Comment by jeorgen** [comment]
You can do the PR! What about having two entry points for scripts? E.g. ./bin/pad_videos_by_sound_track and ./bin/trim_videos_by_sound_track?

I think align_videos_by_soundtrack is a reasonably good name for the package.

**Comment by hhsprings** [comment]
> What about having two entry points for scripts? E.g. ./bin/pad_videos_by_sound_track and ./bin/trim_videos_by_sound_track?

To make many entry points is good for us, but I doubt if it is necessary to have two entry points of what you say. The needs of pad and trim for us are perhaps 50:50, I think. I think that scripts should always return both values. how about that? (I think that it is easy to understand by considering the output in the JSON format, if the scripts produce both, the user only has to choose this as he likes.)

> I think align_videos_by_soundtrack is a reasonably good name for the package.

Agreed. FYI, If it is so, and if the module name is `align.py`, the user of the library will use it as follows:
```python
from align_videos_by_soundtrack.align import SyncDetector

with SyncDetector(...) as sd:
    res = sd.align(...)
```

**Comment by hhsprings** [comment]
`./bin/get_editinfo_by_sound_track`, how about? (Or, `./bin/get_aligninfo_by_sound_track`)

**Comment by jeorgen** [comment]
./bin/alignment_info_by_sound_track ?

**Comment by hhsprings** [comment]
`./bin/alignment_info_by_sound_track`, ok, sounds good.
