### ISSUE TITLE
About output format (especially for json), and arguments help

### ISSUE THREAD

**Issue by hhsprings** [jeorgen/align-videos-by-sound#8]
Even if you say "align", depending on the purpose, some people like to use for "crop" like you, others like to use for "pad" like me.

If we apply this script to multiple files, we are somewhat annoying if we give preferential treatment to either one. So, I'd like the "align" method to be able to return both (or one) in a mode dependent manner. And how about outputting json as well as both "crop" and "pad"?

Another thing, I did not add "help" to "parser.add_argument" with "pull request" so far because I am not a native English speaker, in fact it is "help" and a detailed explanation I want to do. In particular, "max_misalignment" and "known_delay_ge_map" will be confusing for many users without detailed explanation. (Please note that PR and this "issue" and English of the commit log are struggling while using the google translation.)

**Comment by jeorgen** [comment]
JSON could both output "pad" and "trim" (I think "trim" is a better word than "crop" and have switched to it in the doc output and Readme).
In the case of "trim", it can be output with the numbers that the JSON has now, which are calculated from the latest starting video. With regards to "pad" one will have to calculate from the earliest starting file I guess?

**Comment by hhsprings** [comment]
> one will have to calculate from the earliest starting file I guess?

The value returning by the current version of SyncDetector#align is already for "pad", but I think it can calculate both "pad" and "crop".

**Comment by hhsprings** [comment]
What do you do about "help"? If it is okay with my funny English, I will add it temporarily, what do you think? I am a Japanese, so I can not write fancy English, and it may be a misunderstanding expression.

**Comment by jeorgen** [comment]
I think you should write as best you can! I can always make it better afterwards. I think you and I are the only ones using this library right now, anyway :)

**Comment by hhsprings** [comment]
>  I think you and I are the only ones using this library right now, anyway :)

For now. But I reached this from StackOverflow's your discussion, and I think this is outstanding.I wonder if the number of people who read StackOverflow and arrive here like me will increase.

> I think you should write as best you can! I can always make it better afterwards. 

OK, I'll try it.
